-- Erhebung: Zahlungen und Rückforderungen (Fachkonzept Kap. 4).
CREATE TABLE zahlung (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aktenzeichen        VARCHAR(40)  NOT NULL,
    unternehmen_kennung VARCHAR(12)  NOT NULL,
    dienststelle        VARCHAR(8)   NOT NULL,
    art                 VARCHAR(16)  NOT NULL,
    betrag_cent         BIGINT       NOT NULL,
    wertstellung        DATE         NOT NULL,
    zahlungsweg         VARCHAR(16)  NOT NULL,
    erfasst_von         VARCHAR(120) NOT NULL,
    erfasst_am          TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_zahlung_aktenzeichen ON zahlung (aktenzeichen);

CREATE TABLE rueckforderung (
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aktenzeichen                      VARCHAR(40) NOT NULL UNIQUE,
    unternehmen_kennung               VARCHAR(12) NOT NULL,
    dienststelle                      VARCHAR(8)  NOT NULL,
    bescheid_kennung                  VARCHAR(48) NOT NULL,
    betrag_cent                       BIGINT      NOT NULL,
    bekanntgabe                       DATE        NOT NULL,
    faelligkeit                       DATE        NOT NULL,
    zustand                           VARCHAR(12) NOT NULL,
    saeumniszuschlag_festgesetzt_cent BIGINT,
    beglichen_am                      DATE,
    angelegt_am                       TIMESTAMP WITH TIME ZONE NOT NULL
);
